# Generated by Django 4.0.1 on 2022-01-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('grado_de_escolaridad', models.CharField(choices=[('p', 'Primaria'), ('s', 'Secundaria'), ('tm', 'Técnico Medio'), ('pre', 'Preuniversitario'), ('ns', 'Nivel Superior')], max_length=3)),
                ('peso_corporal', models.FloatField()),
            ],
        ),
    ]
