# Generated by Django 4.0.1 on 2022-01-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='peso_corporal',
            field=models.FloatField(verbose_name='Peso corporal (Kg)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='intereses_personales',
            field=models.ManyToManyField(to='encuestas.InteresesPersonales'),
        ),
    ]
