# Generated by Django 4.0.1 on 2022-01-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_interesespersonales_alter_encuesta_peso_corporal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InteresesPersonales',
            new_name='InteresPersonal',
        ),
    ]
