# Generated by Django 4.0.1 on 2022-01-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_rename_interesespersonales_interespersonal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interespersonal',
            options={'verbose_name_plural': 'Intereses Personales'},
        ),
    ]
